name: Developer_branch_CI
on:
  push:
    branches:
      - 'XPNS-*'
env:
  service_name: expense_frontend

jobs:
  CI_Steps:
    uses: Sdevops-prac/github-actions/.github/workflows/Developer_branch_CI.yml@main


